/*
 * system_error_code.h
 *
 *  Created on: Nov 5, 2015
 *      Author: root
 */

#ifndef SYSTEM_ERROR_CODE_H_
#define SYSTEM_ERROR_CODE_H_

typedef enum{
    SYS_ERROR_CODE_MIN = 0, //Reserved
	//*********ERROR CODE FOR COMM**************//
	SYS_ERROR_LKJ_COMM_FAILURE,//added
	SYS_ERROR_RT_INFO_RESOLVING_FAILURE,//
	SYS_ERROR_STATUS_INFO_RESOLVING_FAILURE,//added
	SYS_ERROR_BASEDATA_RECEIVE_FAILURE,
	SYS_ERROR_STATION_INFO_RECEIVE_FAILURE,
	SYS_ERROR_JIESHI_INFO_RECEIVE_FAILURE,
	SYS_ERROR_ROUTE_EXTRACT_FAILURE,
	SYS_ERROR_COMM_SOFTWARE_ERROR,//
	//*********ERROR CODE FOR CORE**************//
	SYS_ERROR_CAN_FAILURE,
	SYS_ERROR_OPTIMIZE_FAILURE,
	SYS_ERROR_CORE_SOFTWARE_ERROR,
	//*********ERROR CODE FOR VOTE**************//
	SYS_ERROR_REGISTER_FAILURE,
	SYS_ERROR_NO_HEARTBEAT_COMM_MAIN,
	SYS_ERROR_NO_HEARTBEAT_COMM_BOTH,
	SYS_ERROR_NO_HEARTBEAT_CORE,
	SYS_ERROR_NO_HEARTBEAT_CONTROLLER_MAIN,
	SYS_ERROR_NO_CLOSED_FEEDBACK_FAILURE,
	SYS_ERROR_VOTE_SOFTWARE_ERROR,
	//*********ERROR CODE FOR COMM**************//
	SYS_ERROR_CODE_MAX
} SYSTEM_ERROR_CODE;



#endif /* SYSTEM_ERROR_CODE_H_ */

